# Generated by Django 3.2.9 on 2021-11-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorozatplanetblog', '0002_post_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
