# Generated by Django 3.2.9 on 2021-11-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorozatplanetblog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link Above', max_length=255),
        ),
    ]
